### ISSUE TITLE
Cast required for DateTime fields in Creation Dialog

### ISSUE THREAD

**Issue by alex-boehm** [Flowpack/Flowpack.NodeTemplates#16]
# Description
The value of an DateTime field in creation dialog can't be given to the inspector field without cast to an DateTime object.

Error message during creation of a new node (without cast):
Exception in line 259 of /MyProject/Packages/Libraries/neos/utility-objecthandling/Classes/ObjectAccess.php: Argument 1 passed to Neos\ContentRepository\Domain\Model\Node_Original::setHiddenAfterDateTime() must be an instance of DateTime or null, string given, called in /MyProject/Packages/Libraries/neos/utility-objecthandling/Classes/ObjectAccess.php on line 259

# Steps to Reproduce

1.  Define DateTime field in Creation Dialog

````
(...)
creationDialog:
  elements:
    _hiddenAfterDateTime:
        type: DateTime
          ui:
            label: i18n
            editor: 'Neos.Neos/Inspector/Editors/DateTimeEditor'
            editorOptions:
              format: 'd.m.Y'
````

2. Define options in yaml
````
(...)
options:
    template:
      properties:
        _hiddenAfterDateTime: "${data._hiddenAfterDateTime}"
````

# Expected behavior

The date set in creation dialog is also set in corresponding inspector field

# Actual behavior
"Argument 1 passed to .... must be an instance of DateTime or null, string given."

Requires cast to DateTime object:
````
 options:
    template:
      properties:
        _hiddenAfterDateTime: "${Date.create(data._hiddenAfterDateTime)}"
````

# Affected Versions
Neos: 4.0.6
NodeTemplates: 1.0.0
