### ISSUE TITLE
Setting the title of the generated node seems not possible

### ISSUE THREAD

**Issue by daniellienert** [Flowpack/Flowpack.NodeTemplates#20]
Given the following configuration: 

```
  ui:
    label: Author
    icon: icon-user
    creationDialog:
      elements:
        title: ~
        firstName:
          type: string
          ui:
            label: 'Vorname'
            editor: 'Neos.Neos/Inspector/Editors/TextFieldEditor'
        lastName:
          type: string
          ui:
            label: 'Nachname'
            editor: 'Neos.Neos/Inspector/Editors/TextFieldEditor'
  options:
    template:
      properties:
        title: '${data.lastName + ", " + data.firstName}'
```

the title of the generated page is not set.
