### ISSUE TITLE
FEATURE: `withContext`

### ISSUE THREAD

**Issue by mhsdesign** [Flowpack/Flowpack.NodeTemplates#36]
It would be great, if one could define in `withContext` an additional global context, which is merged with the other values like `triggeringNode `

```
  options:
    template:
      withContext:
        fooReferenceNode: '${q(triggeringNode).find("#" + data.fooReference).get(0)}'
```

this way frequently computed values can be easily defined once at the top and dont need to be recomputed which might speed up performance marginally but mainly increases readability
