### ISSUE TITLE
FEATURE: Create node template definition yaml dump from node subtree 

### ISSUE THREAD

**Issue by mhsdesign** [Flowpack/Flowpack.NodeTemplates#37]
(i have a prototype already locally and will create a pr soonish)

when creating a more complex node template, to create multiple pages and content elements, it can be helpful to take the current node subtree as reference. For this case a command controller would be great.

```
flow nodeTemplate:fromSubtree 136a646c-b2d5-4475-8e24-b25727aa7913 --workspaceName=live
```  

```
Your.NodeType:
  options:
    template:
      childNodes:
        page0:
          name: page-0
          type: Foo.Bar:Page
          properties:
            title: 'my page'
            uriPathSegment: my-page
            # someReference -> Reference of NodeTypes (Neos.Neos:Document) with value Node(13f5e86b-7b0e-4a7f-9a8a-af6bdf1c1913)
          childNodes:
            page0:
              name: page-0
              type: Foo.Bar:Pag
              properties: ...
              childNodes:
                 mainContentCollection:
                   name: main
                   childNodes: ...
```
