### ISSUE TITLE
NodeCreation: `null` child nodes lead to an Exception 

### ISSUE THREAD

**Issue by fdsis** [Flowpack/Flowpack.NodeTemplates#71]
It is not possible to overwrite an existing Configuration and setting child nodes to `null`.

`./flow nodeTypes:show Agency.Base:Content.Bla --path options.template` returns: 
```
childNodes:
    mainContentCollection:
        name: content
        childNodes:
            headline:
                type: 'Vendor.Website:Content.Bla'
            text: null
            buttonArea: null
```

https://github.com/Flowpack/Flowpack.NodeTemplates/blob/72777b5905d385fea22f193bbd52d432c97784e5/Classes/Domain/TemplateConfiguration/TemplateConfigurationProcessor.php#L113 (suggestion by @mhsdesign)
