### ISSUE TITLE
BUG: Property convert not used when accessing values like `data.image` in eel

### ISSUE THREAD

**Issue by mhsdesign** [Flowpack/Flowpack.NodeTemplates#77]
This patter doesnt work currently

```yaml
  properties:
    image:
      type: ImageInterface
      ui:
         showInCreationDialog: true
  options:
    template:
      properties:
        imageCaption: '${data.image.copyrightNotice}'
```

as `data.image` is not converted. The dump looks like:

```
array(2)
  '__identity' => 4567890,
  '__type' => 'ImageVariant' 
```

related: https://github.com/Flowpack/Flowpack.NodeTemplates/issues/61

version: 2.x
