### ISSUE TITLE
DISCUSSION: Template referencing within templates

### ISSUE THREAD

**Issue by robinroloff** [Flowpack/Flowpack.NodeTemplates#83]
I would like to add a feature, where you can put single parts of a template into a different yaml file, which can then be referenced within nodes.
Example:
Node 1 has the following structure:
```
contentcollection:
  card:
    headline
    text
    image
```
Node 2 has the following structure:
```
contentcollection:
  headline
  text
  image
  
```
I would like to be able to extract the "headline, text, image" part and insert it everywhere in different templates
something like: 

```
contentCollection:   
    childNodes:
        $ref: 'resource://My.Package:Templates/Template.yaml'
```

Template.yaml would then look like:
```
headline:
   type: 'My.Package:Content.Headline'
text:
   type: 'My.Package:Content.Text'
image:
   type: 'My.Package:Content.Image'
```

What do you guys think?
